package handler

import (
	"context"
	"encoding/json"
	"fmt"
	"goRent/internal/model"
	"goRent/internal/render"
	"io/ioutil"
	"net/http"
	"net/url"
	"strconv"

	"github.com/aws/aws-sdk-go/aws/credentials"
	// "github.com/olivere/elastic/aws"
	// "github.com/olivere/elastic"
	"github.com/olivere/elastic/v7"

	aws "github.com/olivere/elastic/aws/v4"
)

func (m *Repository) Search(w http.ResponseWriter, r *http.Request) {

	// m.CreateProductList()

	if err := render.Template(w, r, "home.page.html", &render.TemplateData{
		Data: nil,
	}); err != nil {
		m.App.Error.Println(err)
	}

}

func (m *Repository) SearchResult(w http.ResponseWriter, r *http.Request) {

	awsSigningFn := awsSigning(m.App.AwsAccessKey, m.App.AwsSecretKey, m.App.AwsRegion)
	awsClient, err := awsCreateClient(m.App.AwsUrl, m.App.AwsSniff, awsSigningFn)

	trialSearchQuery(awsClient)

	if err != nil {
		m.App.Error.Println(err)
	}

	var data = make(map[string]interface{})
	var product []model.Product
	var urlquery string
	x := r.URL.Query()
	fmt.Println(x)

	type Autogenerated struct {
		Took     int  `json:"took"`
		TimedOut bool `json:"timed_out"`
		Shards   struct {
			Total      int `json:"total"`
			Successful int `json:"successful"`
			Skipped    int `json:"skipped"`
			Failed     int `json:"failed"`
		} `json:"_shards"`
		Hits struct {
			Total struct {
				Value    int    `json:"value"`
				Relation string `json:"relation"`
			} `json:"total"`
			MaxScore float64 `json:"max_score"`
			Hits     []struct {
				Index  string  `json:"_index"`
				Type   string  `json:"_type"`
				ID     string  `json:"_id"`
				Score  float64 `json:"_score"`
				Source struct {
					ID          string `json:"ID"`
					OwnerID     string `json:"owner_id"`
					Brand       string `json:"brand"`
					Title       string `json:"title"`
					Rating      string `json:"rating"`
					Description string `json:"description"`
					Price       string `json:"price"`
					Image1      string `json:"img1_url"`
					CreateAt    string `json:"create_at"`
					UpdatedAt   string `json:"updated_at"`
				} `json:"_source"`
			} `json:"hits"`
		} `json:"hits"`
	}

	searchkeywords := url.QueryEscape(x["q"][0]) //hockey+sticks

	if len(searchkeywords) == 0 {
		urlquery = `https://search-woo-team-z5lx6ctesbpbgigbrkqcirk2om.ap-southeast-1.es.amazonaws.com/product_list/_search?`
	} else {
		urlquery = `https://search-woo-team-z5lx6ctesbpbgigbrkqcirk2om.ap-southeast-1.es.amazonaws.com/product_list/_search?q=` + searchkeywords
	}

	response, err := http.Get(urlquery)

	if err != nil {
		fmt.Printf("The HTTP request failed with error %s \n", err)
	} else {
		fmt.Println(urlquery)
		dataResponse, _ := ioutil.ReadAll(response.Body)
		fmt.Println("[GET] request fired from search result route:", response.StatusCode)
		response.Body.Close()

		if response.StatusCode == 200 {

			var p Autogenerated
			err = json.Unmarshal(dataResponse, &p)
			if err != nil {
				fmt.Println("error processing json files")
			}

			if p.Hits.Total.Value == 0 {
				//no results found, do something
				fmt.Println("no results found at all")
			} else {
				fmt.Println("total number of results", p.Hits.Total.Value)

				for _, v := range p.Hits.Hits {

					productID, err_productiD := strconv.Atoi(v.Source.ID)
					if err_productiD != nil {
						m.App.Error.Println(err_productiD)
					}

					productOwnerID, err_productOwnerID := strconv.Atoi((v.Source.OwnerID))
					if err_productOwnerID != nil {
						m.App.Error.Println(err_productOwnerID)
					}

					productRating, err_productRating := strconv.ParseFloat(v.Source.Rating, 32)
					if err_productRating != nil {
						m.App.Error.Println(err_productRating)
					}
					productPrice, err_productPrice := strconv.ParseFloat(v.Source.Price, 32)
					if err_productPrice != nil {
						m.App.Error.Println(err_productPrice)
					}

					var jsonImage = []string{v.Source.Image1}

					product = append(product, model.Product{ID: productID, OwnerID: productOwnerID, Brand: v.Source.Brand, Title: v.Source.Title,
						Rating: float32(productRating), Description: v.Source.Description, Price: float32(productPrice), Images: jsonImage})

				}
				for _, v := range product {
					fmt.Println("This is the product title", v.Title)
					fmt.Println("This is the product brand", v.Brand)
					fmt.Println("This is the product description", v.Description)
					fmt.Println("This is the product price", v.Price)
					fmt.Println("This is the product rating", v.Rating)
					fmt.Println("---- ---- ----")
					fmt.Println("this is the product image link", v.Images)
				}
			}

		} else {
			fmt.Println("get request failed")
			fmt.Println(string(dataResponse))
		}
	}

	data["product"] = product

	if err := render.Template(w, r, "searchresult.page.html", &render.TemplateData{
		Data: data,
	}); err != nil {
		m.App.Error.Println(err)
	}

}

func awsSigning(awsAccesKey, awsSecretKey, awsRegoin string) *http.Client {

	signingClient := aws.NewV4SigningClient(credentials.NewStaticCredentials(
		awsAccesKey,
		awsSecretKey,
		"",
	), awsRegoin)

	return signingClient

}

func awsCreateClient(url string, sniff bool, signingClient *http.Client) (*elastic.Client, error) {

	client, err := elastic.NewClient(
		elastic.SetURL(url),
		elastic.SetSniff(sniff),
		elastic.SetHealthcheck(false),
		elastic.SetHttpClient(signingClient),
	)
	if err != nil {
		// log.Fatal(err)
		return client, err
	}

	return client, nil

}

func trialSearchQuery(client *elastic.Client) {

	stringQuery := elastic.NewQueryStringQuery("wedding dress")
	searchResult, err := client.Search().
		Index("sample_product_list"). // search in index "tweets"
		// Query(termQuery).             // specify the query
		Query(stringQuery).      // specify the query
		Pretty(true).            // pretty print request and response JSON
		Do(context.Background()) // execute

	if err != nil {
		fmt.Println("error from search", err)
	}

	var product []model.ElasticSearchProductSample

	for _, hit := range searchResult.Hits.Hits {

		var t model.ElasticSearchProductSample

		if err := json.Unmarshal(hit.Source, &t); err != nil {
			// log.Errorf("ERROR UNMARSHALLING ES SUGGESTION RESPONSE: %v", err)
			continue
		}
		if err != nil {
			// Deserialization failed
			fmt.Println("error unmarshaling json", err)

		}
		product = append(product, t)

	}

	fmt.Println(product)

}
